name: PR check

on:
  pull_request:
    branches: v0

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run fmt
      - run: npm run lint
      - run: npm run test
